import { Theme } from "@/theme/types";
import type {
  HexColor,
  NetGraphConfig,
  NetGraphData,
} from "@carlsonerik/netgraph";

export const getNetworkGraphConfig = (
  theme: Theme,
  graphWidth: number
): NetGraphConfig => {
  const isSmallScreen = graphWidth < 500;
  return {
    showSimulation: false,
    color: {
      node: "#1D4ED8",
      link: theme.colors.text as HexColor,
      highlight: "#1d46b7",
      groups: ["#FF1E56", "#F97316", "#34D399"],
    },
    highlight: {
      enabled: true,
      type: "all",
      node: {
        highlightOthers: false,
        size: 0,
      },
      link: {
        weight: 4,
        arrowSize: 0,
        defocusOpacity: 0.2,
        style: "solid",
      },
    },
    node: {
      radius: 8,
      useFillImages: false,
    },
    link: {
      style: "solid",
      weight: 1,
    },
    tooltips: {
      enabled: false,
    },
    forces: {
      charge: {
        enabled: true,
        strength: -75,
        distanceMin: 1,
        distanceMax: isSmallScreen ? 80 : 150,
      },
      collide: {
        enabled: true,
        strength: 1,
        iterations: 1,
      },
      link: {
        enabled: true,
        distance: isSmallScreen ? 80 : 150,
        iterations: 1,
      },
      xForce: {
        enabled: false,
        strength: 0.15,
        x: 0,
      },
      yForce: {
        enabled: false,
        strength: 0.15,
        y: 0,
      },
    },
    directionality: {
      arrows: {
        enabled: false,
        size: 0,
      },
    },
  };
};

export const NETWORK_GRAPH_DATA: NetGraphData = {
  nodes: [
    {
      id: "node-1",
      name: "Kernel",
      radius: 26,
      weight: 12,
      group: "top-performer",
    },
    {
      id: "node-2",
      name: "Pulse",
      radius: 22,
      weight: 12,
      group: "top-performer",
    },
    {
      id: "node-3",
      name: "Vector",
      radius: 22,
      weight: 12,
      group: "rising-star",
    },
    {
      id: "node-4",
      name: "Signal",
      radius: 20,
      weight: 12,
      group: "rising-star",
    },
    {
      id: "node-5",
      name: "Harvester",
      radius: 18,
      weight: 12,
      group: "rising-star",
    },
    { id: "node-6", name: "Silo", radius: 14 },
    { id: "node-7", name: "Panorama", radius: 14 },
    { id: "node-8", name: "Aurora", radius: 12 },
    { id: "node-9", name: "Prism", radius: 12 },
    { id: "node-10", name: "Atlas", radius: 10 },
    {
      id: "node-11",
      name: "Relay",
      radius: 16,
      weight: 12,
      group: "solid-performer",
    },
    { id: "node-12", name: "Bridge", radius: 16, weight: 12 },
    {
      id: "node-13",
      name: "Sentinel",
      radius: 18,
      weight: 12,
      group: "solid-performer",
    },
    {
      id: "node-14",
      name: "Guardian",
      radius: 18,
      weight: 12,
      group: "solid-performer",
    },
    {
      id: "node-15",
      name: "Chronicle",
      radius: 24,
      weight: 12,
      group: "top-performer",
    },
    { id: "node-16", name: "Nexus", radius: 12 },
    { id: "node-17", name: "Forge", radius: 10 },
    { id: "node-18", name: "Beacon East", radius: 12 },
    {
      id: "node-19",
      name: "Nova",
      radius: 20,
      weight: 12,
      group: "rising-star",
    },
    {
      id: "node-20",
      name: "Horizon",
      radius: 24,
      weight: 12,
      group: "top-performer",
    },
    { id: "node-21", name: "Orbit", radius: 12 },
    { id: "node-22", name: "Trace", radius: 10 },
    { id: "node-23", name: "Pulse North", radius: 8 },
    {
      id: "node-24",
      name: "Quantum",
      radius: 18,
      weight: 12,
      group: "solid-performer",
    },
    { id: "node-25", name: "Beacon South", radius: 14 },
  ],
  links: [
    { source: "node-1", target: "node-2" },
    { source: "node-1", target: "node-3" },
    { source: "node-1", target: "node-8" },
    { source: "node-2", target: "node-4" },
    { source: "node-2", target: "node-5" },
    { source: "node-2", target: "node-7" },
    { source: "node-3", target: "node-6" },
    { source: "node-3", target: "node-7" },
    { source: "node-3", target: "node-11" },
    { source: "node-4", target: "node-6" },
    { source: "node-4", target: "node-8" },
    { source: "node-4", target: "node-9" },
    { source: "node-5", target: "node-7" },
    { source: "node-5", target: "node-8" },
    { source: "node-5", target: "node-10" },
    { source: "node-5", target: "node-11" },
    { source: "node-6", target: "node-8" },
    { source: "node-6", target: "node-9" },
    { source: "node-6", target: "node-11" },
    { source: "node-6", target: "node-14" },
    { source: "node-7", target: "node-9" },
    { source: "node-7", target: "node-10" },
    { source: "node-7", target: "node-13" },
    { source: "node-8", target: "node-10" },
    { source: "node-8", target: "node-11" },
    { source: "node-8", target: "node-13" },
    { source: "node-8", target: "node-15" },
    { source: "node-9", target: "node-11" },
    { source: "node-9", target: "node-12" },
    { source: "node-9", target: "node-14" },
    { source: "node-9", target: "node-15" },
    { source: "node-10", target: "node-12" },
    { source: "node-10", target: "node-13" },
    { source: "node-10", target: "node-15" },
    { source: "node-11", target: "node-13" },
    { source: "node-11", target: "node-14" },
    { source: "node-12", target: "node-14" },
    { source: "node-12", target: "node-15" },
    { source: "node-13", target: "node-14" },
    { source: "node-13", target: "node-15" },
    { source: "node-2", target: "node-16" },
    { source: "node-3", target: "node-16" },
    { source: "node-4", target: "node-16" },
    { source: "node-5", target: "node-16" },
    { source: "node-6", target: "node-17" },
    { source: "node-7", target: "node-17" },
    { source: "node-8", target: "node-17" },
    { source: "node-3", target: "node-18" },
    { source: "node-5", target: "node-18" },
    { source: "node-10", target: "node-18" },
    { source: "node-4", target: "node-19" },
    { source: "node-6", target: "node-19" },
    { source: "node-8", target: "node-19" },
    { source: "node-9", target: "node-19" },
    { source: "node-11", target: "node-19" },
    { source: "node-1", target: "node-20" },
    { source: "node-14", target: "node-20" },
    { source: "node-15", target: "node-20" },
    { source: "node-13", target: "node-20" },
    { source: "node-2", target: "node-21" },
    { source: "node-4", target: "node-21" },
    { source: "node-7", target: "node-21" },
    { source: "node-9", target: "node-21" },
    { source: "node-12", target: "node-21" },
    { source: "node-3", target: "node-22" },
    { source: "node-5", target: "node-22" },
    { source: "node-8", target: "node-22" },
    { source: "node-11", target: "node-22" },
    { source: "node-15", target: "node-22" },
    { source: "node-4", target: "node-23" },
    { source: "node-6", target: "node-23" },
    { source: "node-9", target: "node-23" },
    { source: "node-10", target: "node-23" },
    { source: "node-12", target: "node-23" },
    { source: "node-1", target: "node-24" },
    { source: "node-3", target: "node-24" },
    { source: "node-6", target: "node-24" },
    { source: "node-9", target: "node-24" },
    { source: "node-14", target: "node-24" },
    { source: "node-2", target: "node-25" },
    { source: "node-5", target: "node-25" },
    { source: "node-7", target: "node-25" },
    { source: "node-11", target: "node-25" },
    { source: "node-13", target: "node-25" },
  ],
};
